apiVersion: v1
kind: Pod
metadata:
  name: centos-tool
spec:
  nodeSelector:
    kubernetes.io/hostname: 192.168.10.242
  containers:
  - name: main
    image: centos
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: "20Mi"
    command: ["dd","if=/dev/zero","of=/dev/null"]
